
#AUTH
    #log in
POST http://localhost:5000/auth/login
Content-Type: application/json

{"email": "johnny@gmail.com",
"password": "j123"
}

###
    #logout

    
GET http://localhost:5000/auth/logout

###
    #create

POST http://localhost:5000/auth/create
Content-Type: application/json

{ "name":"Eliud",
    "email": "elly45@gmail.com",
"password": "j123"
}
###

#USERS
    #get all users
GET http://localhost:5000/users
###
    #get user by id
GET http://localhost:5000/users/2c7ab450-72e1-4e18-b931-9c34a8fd7fe1

###
    #patch user by id
###
    #delete user by id
###


#COMMENTS
    #get all comments
GET http://localhost:5000/comments
###
    #get comments by id
GET http://localhost:5000/comments/c7
###
    #create comment
POST http://localhost:5000/comments/create

Content-Type: application/json

{ "name":"Eliud",
    "email": "elly45@gmail.com",
"password": "j123"
}


###
    #patch comments by id
###
    #delete comments by id
###

