
#AUTH
    #log in
POST http://localhost:5000/auth/login
Content-Type: application/json

{"email": "johnny@gmail.com",
"password": "j123"
}

###
    #logout

    
GET http://localhost:5000/auth/logout

###
    #create
###

#USERS
    #get all users
###
    #get user by id
###
    #patch user by id
###
    #delete user by id
###


http://localhost:5000/users